/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package aaa.statusbar.hidesimicon;

public final class R {
  public static final class drawable {
    public static final int stat_sys_preferred_sim_1=0x7f010000;
    public static final int stat_sys_preferred_sim_2=0x7f010001;
    public static final int stat_sys_preferred_sim_3=0x7f010002;
    public static final int stat_sys_preferred_sim_call=0x7f010003;
    public static final int stat_sys_preferred_sim_heart=0x7f010004;
    public static final int stat_sys_preferred_sim_home=0x7f010005;
    public static final int stat_sys_preferred_sim_internet=0x7f010006;
    public static final int stat_sys_preferred_sim_msg=0x7f010007;
    public static final int stat_sys_preferred_sim_office=0x7f010008;
  }
}